"""Strategy Base Framework - Signal, BaseStrategy, StrategyRegistry"""
from __future__ import annotations
import pandas as pd
import numpy as np
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from datetime import datetime, timezone


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    instrument: str = ""
    direction: str = ""
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    confidence: float = 0.0
    strategy_name: str = ""
    timeframe: str = ""
    session: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict = field(default_factory=dict)

    def risk_reward_ratio(self) -> float:
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        return reward / risk if risk > 0 else 0.0


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Subclass this to implement new strategies (consolidation breakout,
    supply/demand, momentum, range, etc.).
    """
    
    def __init__(self, name: str, description: str = ""):
        self.name = name
        self.description = description
    
    @abstractmethod
    def detect_pattern(self, df: pd.DataFrame, **kwargs) -> pd.DataFrame:
        """
        Analyze the DataFrame and add pattern detection columns.
        Must add at minimum: 'pattern_detected' (bool), 'pattern_type' (str)
        Returns the annotated DataFrame.
        """
        pass
    
    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, instrument: str,
                         timeframe: str, **kwargs) -> List[Signal]:
        """
        Generate buy/sell signals from the analyzed DataFrame.
        Returns a list of Signal objects.
        """
        pass
    
    @abstractmethod
    def get_zones(self, df: pd.DataFrame) -> List[Dict]:
        """
        Return consolidation/supply/demand zones for visualization.
        Each zone: {'start_idx': int, 'end_idx': int, 'top': float, 'bottom': float,
                    'type': str, 'color': str}
        """
        pass
    
    def calculate_targets(self, entry: float, direction: str, df: pd.DataFrame,
                          max_sl_pct: float = 0.02) -> Tuple[float, float]:
        """
        Calculate SL and TP based on recent HH/HL/LL/LH structure.
        SL capped at max_sl_pct (default 2%).
        """
        swing_points = self._find_swing_points(df)
        
        if direction == "BUY":
            # SL below last HL or LL
            lows = [sp["price"] for sp in swing_points if sp["type"] in ("HL", "LL")]
            sl = min(lows[-3:]) if lows else entry * (1 - max_sl_pct)
            # Cap SL at max_sl_pct
            if (entry - sl) / entry > max_sl_pct:
                sl = entry * (1 - max_sl_pct)
            # TP at last HH or next resistance
            highs = [sp["price"] for sp in swing_points if sp["type"] in ("HH", "LH")]
            tp = max(highs[-3:]) if highs else entry * (1 + 2 * (entry - sl) / entry)
        else:  # SELL
            # SL above last HH or LH
            highs = [sp["price"] for sp in swing_points if sp["type"] in ("HH", "LH")]
            sl = max(highs[-3:]) if highs else entry * (1 + max_sl_pct)
            if (sl - entry) / entry > max_sl_pct:
                sl = entry * (1 + max_sl_pct)
            # TP at last LL or next support
            lows = [sp["price"] for sp in swing_points if sp["type"] in ("HL", "LL")]
            tp = min(lows[-3:]) if lows else entry * (1 - 2 * (sl - entry) / entry)
        
        return sl, tp
    
    def _find_swing_points(self, df: pd.DataFrame, lookback: int = 5) -> List[Dict]:
        """
        Identify swing highs and swing lows, then classify as HH/HL/LH/LL.
        """
        swing_points = []
        
        for i in range(lookback, len(df) - lookback):
            # Swing High
            if df["high"].iloc[i] == df["high"].iloc[i-lookback:i+lookback+1].max():
                swing_points.append({
                    "index": i, "price": df["high"].iloc[i],
                    "time": df.index[i], "swing": "high", "type": None
                })
            # Swing Low
            if df["low"].iloc[i] == df["low"].iloc[i-lookback:i+lookback+1].min():
                swing_points.append({
                    "index": i, "price": df["low"].iloc[i],
                    "time": df.index[i], "swing": "low", "type": None
                })
        
        # Classify swing points as HH/HL/LH/LL
        last_high = None
        last_low = None
        for sp in swing_points:
            if sp["swing"] == "high":
                if last_high is not None:
                    sp["type"] = "HH" if sp["price"] > last_high else "LH"
                else:
                    sp["type"] = "HH"
                last_high = sp["price"]
            elif sp["swing"] == "low":
                if last_low is not None:
                    sp["type"] = "HL" if sp["price"] > last_low else "LL"
                else:
                    sp["type"] = "HL"
                last_low = sp["price"]
        
        return swing_points


# Strategy Registry
class StrategyRegistry:
    """Registry to manage and select trading strategies."""
    
    def __init__(self):
        self._strategies: Dict[str, BaseStrategy] = {}
    
    def register(self, strategy: BaseStrategy):
        self._strategies[strategy.name] = strategy
        print(f"  📌 Registered strategy: {strategy.name}")
    
    def get(self, name: str) -> BaseStrategy:
        if name not in self._strategies:
            raise ValueError(f"Strategy '{name}' not found. Available: {list(self._strategies.keys())}")
        return self._strategies[name]
    
    def list_strategies(self) -> List[str]:
        return list(self._strategies.keys())
    
    def scan_all(self, df: pd.DataFrame, instrument: str,
                 timeframe: str, **kwargs) -> List[Signal]:
        """Run all registered strategies and collect signals."""
        all_signals = []
        for name, strategy in self._strategies.items():
            try:
                signals = strategy.generate_signals(df, instrument, timeframe, **kwargs)
                all_signals.extend(signals)
            except Exception as e:
                print(f"  ⚠️ {name} error: {e}")
        return all_signals

# Global registry
strategy_registry = StrategyRegistry()